Repository aicoe-aiops/data-science-workflows, pull requests merged in 2020-06, with the labels that each got.

#2 add template link to readme
  README.md
Labels: approved, size/XS

#6 Add instructions for thoth bots
  Thoth-bots.md
Labels: size/M

#4 Upload ascii doc for DS Workflow
  data science workflow blog.adoc
Labels: size/M

#10 Argo automation docs
  Automating via Argo.md
  assets/images/workflow_artifacts.png
  assets/images/workflow_diagram.png
  assets/images/workflow_drilldown.png
Labels: approved
