Repository aicoe-aiops/data-science-workflows, pull requests merged in 2021-12, with the labels that each got.

#71 Add meteorizing project repos to Deliverables
  docs/getting-started.md
Labels: size/XS

#80 Update project-structure.md
  docs/project-structure.md
Labels: approved, size/L, lgtm

#79 Add odh + opf intro
  docs/odh_and_opf.md
Labels: approved, size/S

#78 add guide on deploying models using seldon
  docs/deploy-models-using-seldon.md
  docs/getting-started.md
  public/assets/deploy-models-using-seldon/create-deployment.png
  public/assets/deploy-models-using-seldon/create-route.png
  public/assets/deploy-models-using-seldon/create-secret.png
Labels: approved, size/M

#83 added a short doc on Thoth
  docs/thoth-tools.md
Labels: approved, size/S

#85 Add remote storage doc
  docs/remote-storage.md
Labels: size/XS, approved

#86 small edits to remote-storage
  docs/remote-storage.md
Labels: size/XS, approved, lgtm

#84 Update getting-started
  docs/boards-and-issues.md
  docs/getting-started.md
Labels: approved, size/L, lgtm

#82 JH on opf
  docs/JH_access.md
  public/assets/Setup_Environment/container_size.png
  public/assets/Setup_Environment/env_variables.png
  public/assets/Setup_Environment/event_logs.png
  public/assets/Setup_Environment/green_icon.png
  public/assets/Setup_Environment/jh_start_page.png
  public/assets/Setup_Environment/notebook_server.png
  public/assets/Setup_Environment/opf_login.png
  public/assets/Setup_Environment/running_tab.png
Labels: approved, size/M, lgtm

#88 restructure docs directory and toc
  _toc.yml
  docs/develop_collaborate/automated-pipelines.md
  docs/develop_collaborate/automating-via-argo-blog.adoc
  docs/develop_collaborate/create_and_deploy_jh_image.md
  docs/develop_collaborate/meteorize.md
  docs/develop_collaborate/thoth-tools.md
  docs/project_structure/aiops-projects.md
  docs/project_structure/boards-and-issues.md
  docs/project_structure/data-science-workflow-blog.adoc
  docs/project_structure/getting-started.md
  docs/project_structure/guidelines-for-reviewing-datascience-code.md
  docs/project_structure/how-to-contribute.md
  docs/project_structure/project-document-template.md
  docs/project_structure/project-structure.md
  docs/serving_monitoring/deploy-models-using-seldon.md
  docs/serving_monitoring/monitor-jh.md
  docs/setup_environment/JH_access.md
  docs/setup_environment/odh_and_opf.md
  docs/setup_environment/remote-storage.md
  docs/setup_environment/thoth.md
  docs/visualization/data-visualization-best-practices.md
Labels: approved, size/M

#87 added a document on experiment tracking using kfp
  docs/track-metrics-using-kubeflow.md
  public/assets/track-metrics-using-kubeflow/compare-runs.png
  public/assets/track-metrics-using-kubeflow/metrics.png
Labels: approved, size/M

#89 some fixes for jupyterbook
  README.md
  docs/develop_collaborate/automated-pipelines.md
  docs/project_structure/boards-and-issues.md
  docs/setup_environment/thoth.md
Labels: approved, size/S, lgtm

#90 Update readme and supporting docs
  README.md
  _toc.yml
  docs/develop_collaborate/how-to-contribute.md
  docs/develop_collaborate/track-metrics-using-kubeflow.md
  docs/project_structure/boards-and-issues.md
  docs/serving_monitoring/deploy-custom-model.md
  docs/setup_environment/JH_access.md
  docs/visualization/trino_and_superset.md
Labels: size/M

#92 Fix projects overview link
  docs/develop_collaborate/how-to-contribute.md
Labels: size/XS, approved, lgtm

#93 update docs to fix broken image links
  docs/develop_collaborate/create_and_deploy_jh_image.md
  docs/develop_collaborate/track-metrics-using-kubeflow.md
  docs/serving_monitoring/deploy-models-using-seldon.md
  docs/serving_monitoring/monitor-jh.md
  docs/setup_environment/JH_access.md
Labels: size/M, lgtm

#95 Make the documents headings clearer.
  docs/develop_collaborate/meteorize.md
  docs/project_structure/project-structure.md
  docs/serving_monitoring/monitor-jh.md
Labels: approved, size/S, lgtm

#94 update toc
  _toc.yml
Labels: size/S, lgtm

#96 Fix chapter names/links in toc
  _toc.yml
Labels: size/S

#98 fix links in readme
  README.md
Labels: approved, lgtm
