Repository aicoe-aiops/data-science-workflows, pull requests merged in 2021-11, with the labels that each got.

#58 Update README.md
  README.md
Labels: size/XS, approved, lgtm

#59 Fix a few links in the getting started guide
  docs/getting-started.md
Labels: approved, size/S

#60 Add aicoe-ci.yaml and gitignore
  .aicoe-ci.yaml
  .gitignore
Labels: approved, size/L
